#!/bin/sh

set -eu

script_directory="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
repository_path="${CI_PRIMARY_REPOSITORY_PATH:-$(dirname "$script_directory")}"
config_path="$repository_path/Config/Local.xcconfig"

required_settings="
FIREBASE_API_KEY
FIREBASE_APP_ID
FIREBASE_GCM_SENDER_ID
FIREBASE_PROJECT_ID
GOOGLE_IOS_CLIENT_ID
GOOGLE_REVERSED_CLIENT_ID
PICKLY_API_BASE_URL
"

missing_settings=""
for setting in $required_settings; do
    value="$(printenv "$setting" 2>/dev/null || true)"
    case "$value" in
        ""|PASTE_*) missing_settings="$missing_settings $setting" ;;
    esac
done

if [ -n "$missing_settings" ]; then
    echo "error: Xcode Cloud is missing required secret environment variables:$missing_settings" >&2
    exit 1
fi

firebase_sender_id="$(printenv FIREBASE_GCM_SENDER_ID)"
google_ios_client_id="$(printenv GOOGLE_IOS_CLIENT_ID)"
google_reversed_client_id="$(printenv GOOGLE_REVERSED_CLIENT_ID)"

case "$google_ios_client_id" in
    "$firebase_sender_id"-*.apps.googleusercontent.com)
        google_ios_client_key="${google_ios_client_id%.apps.googleusercontent.com}"
        ;;
    *)
        echo "error: GOOGLE_IOS_CLIENT_ID does not belong to FIREBASE_GCM_SENDER_ID." >&2
        exit 1
        ;;
esac

if [ "$google_reversed_client_id" != "com.googleusercontent.apps.$google_ios_client_key" ]; then
    echo "error: GOOGLE_REVERSED_CLIENT_ID does not match GOOGLE_IOS_CLIENT_ID." >&2
    exit 1
fi

api_base_url="$(printenv PICKLY_API_BASE_URL)"
case "$api_base_url" in
    https://*) api_base_remainder="${api_base_url#https://}" ;;
    *)
        echo "error: PICKLY_API_BASE_URL must be an HTTPS URL with a host." >&2
        exit 1
        ;;
esac

api_base_host="${api_base_remainder%%/*}"
case "$api_base_host" in
    ""|.*|*.)
        echo "error: PICKLY_API_BASE_URL must be an HTTPS URL with a host." >&2
        exit 1
        ;;
esac

# xcconfig treats // as a comment, so preserve the URL with Xcode's empty
# variable escape. Keep the generated file private and out of build logs.
escaped_api_base_url='https:/$()/'"${api_base_url#https://}"
storage_bucket="$(printenv FIREBASE_STORAGE_BUCKET 2>/dev/null || true)"

umask 077
{
    echo "// Generated by Xcode Cloud. Do not commit."
    for setting in \
        FIREBASE_API_KEY \
        FIREBASE_APP_ID \
        FIREBASE_GCM_SENDER_ID \
        FIREBASE_PROJECT_ID \
        GOOGLE_IOS_CLIENT_ID \
        GOOGLE_REVERSED_CLIENT_ID
    do
        printf '%s = %s\n' "$setting" "$(printenv "$setting")"
    done
    printf 'FIREBASE_STORAGE_BUCKET = %s\n' "$storage_bucket"
    printf 'PICKLY_API_BASE_URL = %s\n' "$escaped_api_base_url"
} > "$config_path"

echo "Prepared Config/Local.xcconfig for the Xcode Cloud build."
